version: '3,8'
services:
  client:
    build: .
    container_name: my_container
    ports:
      - "5173:5173"
    depends_on:
      - api
  
  api:
    build: ./my-app
    container_name: api
    ports: 
      - "3000:3000"

